plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.services)
    alias(libs.plugins.ksp)
}

android {
    namespace 'com.example.arjun.su_bca'

    compileSdk 35

    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.example.arjun.su_bca"
        minSdk 24
        targetSdk 34

        versionCode 7
        versionName "3.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false

            proguardFiles(
                    getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            )
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packaging {
        resources {
            excludes += [
                    'META-INF/atomicfu.kotlin_module',
                    'META-INF/DEPENDENCIES',
                    'META-INF/INDEX.LIST'
            ]
        }
    }

    lint {
        baseline = file("lint-baseline.xml")
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout

    testImplementation libs.junit

    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core

    // Firebase
    implementation platform(libs.firebase.bom)
    implementation libs.firebaseui.firestore
    implementation libs.firebase.firestore
    implementation libs.firebase.auth
    implementation libs.firebase.database
    implementation libs.firebase.messaging

    // CardView
    implementation libs.androidx.cardview

    // CircleImageView
    implementation libs.circleimageview

    // Volley
    implementation libs.volley

    // Room
    implementation libs.room.runtime
    implementation libs.room.ktx
    ksp libs.room.compiler

    // OneSignal
    implementation libs.onesignal

    // Google AI
    implementation libs.generativeai

    // Google Auth
    implementation(libs.google.auth) {
        exclude group: "io.grpc"
    }
}